imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: fos/fos_user.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_js.yml }
    - { resource: jms/jms_serializer.yml }

    # Sonata Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_user.yml }

    # liip
    - { resource: liip/liip_monitor.yml }

    # apc
    #- { resource: ornicar/apc.yml }

    # rmzamora
    - { resource: rmzamora/ckeditor.yml }
    #- { resource: rmzamora/rz/rz_admin.yml }
    #- { resource: rmzamora/rz/rz_user.yml }

    #  egeloen
    - { resource: egeloen/ckeditor.yml }

framework:
    esi: { enabled: true }
    fragments: { path: /_fragment }
    translator: { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale: %locale%
    session: ~

# Twig Configuration
twig:
    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SonataAdminBundle:Form:silex_form_div_layout.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: "/usr/bin/java"
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.rmzamora-build.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.rmzamora-build.jar"
        closure:
            jar: "%kernel.root_dir%/Resources/java/google.closure.jar"
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false
