#
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    use_listener:           true
    use_username_form_type: true
    model_manager_name:     null
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
#
#    registration:
#        confirmation:
#            enabled:    true
#            from_email:
#                address:        registration@rmzamora.com
#                sender_name:    rzamora-sandbox Registration
#            enabled:    true # change to true for required email confirmation
#            template:   FOSUserBundle:Registration:email.txt.twig
#        form:
#            type:               rmzamora_sonataext_user_registration
#            name:               rmzamora_sonataext_user_registration_form
#            validation_groups:  [Registration, Default]
#
#    profile:  # Authentication Form
#        form:
#            type:               rmzamora_sonataext_auth_profile
#            name:               rmzamora_sonataext_auth_profile_form
#            validation_groups:  [Authentication] # Please note : this is not the default value
#
#    resetting:
#        token_ttl: 86400
#        email:
#            from_email: # Use this node only if you don't want the global email address for the resetting email
#                address:        reset@rmzamora.com
#                sender_name:    rzamora-sandbox Reset Password
#            template:   FOSUserBundle:Resetting:email.txt.twig

    service:
        mailer:                 fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~


sonata_user:
    security_acl:     false
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group

    impersonating:
        route:                page_slug
        parameters:           { path: / }

    google_authenticator:
        server:               %sonata_user.google_authenticator.server%
        enabled:              true

    manager_type:             orm

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               rz_user_profile
            name:               rz_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default

        update_password:
                type:               rz_user_update_password
                name:               rz_user_update_password_form

        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
                - { position: left, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
                - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
                - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
            - { route: 'fos_user_security_logout', label: 'Logout', domain: 'SonataUserBundle'}

